name: GH Actions CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  # Specific group naming so CI is only cancelled
  # within same PR or on merge to main
  group: ${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  main_tests:
    if: "github.repository == 'lilyminium/test_mda_condaforge_rtd'"
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
          os: [macOS-latest, ubuntu-latest, windows-latest]
          python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Build information
      run: |
        uname -a
        df -h
        ulimit -a


    # More info on options: https://github.com/conda-incubator/setup-miniconda
    - name: Install conda dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: devtools/conda-envs/test_env.yaml
        add-pip-as-python-dependency: true
        architecture: x64

        mamba-version: "*"
        channels: conda-forge, defaults

        activate-environment: test_mda_condaforge_rtd-test
        auto-update-conda: true
        auto-activate-base: false
        show-channel-urls: true



    - name: Install package
      run: |
        python -m pip install . --no-deps


    - name: Python information

      run: |
        which python
        which pip
        pip list

        conda info
        conda list

    - name: Run tests

      run: |
        pytest -n 4 -v --cov=test_mda_condaforge_rtd --cov-report=xml --color=yes test_mda_condaforge_rtd/tests/

    - name: codecov
      uses: codecov/codecov-action@v2
      with:
        file: coverage.xml
        name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
        verbose: True


  pylint_check:
    if: "github.repository == 'lilyminium/test_mda_condaforge_rtd'"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install Pylint
      run: |
        which pip
        which python
        pip install pylint

    - name: Run Pylint
      env:
        PYLINTRC: .pylintrc
      run: |
        pylint test_mda_condaforge_rtd


  pypi_check:
    if: "github.repository == 'lilyminium/test_mda_condaforge_rtd'"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install setuptools cython numpy twine

    - name: Build package
      run: |
        python setup.py sdist

    - name: Check package build
      run: |
        DISTRIBUTION=$(ls -t1 dist/test_mda_condaforge_rtd-*.tar.gz | head -n 1)
        test -n "${DISTRIBUTION}" || { echo "no distribution dist/test_mda_condaforge_rtd-*.tar.gz found"; exit 1; }
        echo "twine check $DISTRIBUTION"
        twine check $DISTRIBUTION
  
  install_from_source_pip:
    if: "github.repository == 'lilyminium/test_mda_condaforge_rtd'"
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build from source
      run: |
        python --version
        pip install -e ".[test,doc]"

    - name: Check success
      run: |
        python -c "import MDAnalysis as mda; print(f'MDAnalysis version:', mda.__version__)"
        python -c "import test_mda_condaforge_rtd; print('test_mda_condaforge_rtd version:', test_mda_condaforge_rtd.__version__)"


  install_from_source_conda:
    if: "github.repository == 'lilyminium/test_mda_condaforge_rtd'"
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Install conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        add-pip-as-python-dependency: true
        architecture: x64
        auto-update-conda: true
        show-channel-urls: true

        mamba-version: "*"
        channels: conda-forge, defaults

    - name: Build from source
      run: |
        conda create --name test_mda_condaforge_rtd
        conda activate test_mda_condaforge_rtd
        conda env update --name test_mda_condaforge_rtd --file devtools/conda-envs/test_env.yaml
        conda list
        ls docs/
        cat docs/requirements.yaml
        conda env update --name test_mda_condaforge_rtd --file docs/requirements.yaml
        pip install -e .
        conda list

    - name: Check success
      run: |
        conda activate test_mda_condaforge_rtd
        python -c "import MDAnalysis as mda; print(f'MDAnalysis version:', mda.__version__)"
        python -c "import test_mda_condaforge_rtd; print('test_mda_condaforge_rtd version:', test_mda_condaforge_rtd.__version__)"



